theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false
  logo: 
    header: '/assets/images/logo.png'
    footer: ''