[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/plan-du-site/index.html"
to = "/fr/plan-du-site/"

[[redirects]]
from = "/fr/projets/courts-metrages/index.html"
to = "/fr/realisations/courts-metrages/"

[[redirects]]
from = "/fr/biographie/index.html"
to = "/fr/a-propos/"

[[redirects]]
from = "/projets/index.html"
to = "/fr/realisations/"

[[redirects]]
from = "/actualites/index.html"
to = "/fr/actualites/"

[[redirects]]
from = "/fr/projets/index.html"
to = "/fr/realisations/"

[[redirects]]
from = "/accessibilite/index.html"
to = "/fr/accessibilite/"

[[redirects]]
from = "/equipe/index.html"
to = "/fr/equipe/"

[[redirects]]
from = "/organisations/index.html"
to = "/fr/organisations/"

[[redirects]]
from = "/fr/projets/2018-deux-escargots-sen-vont/index.html"
to = "/fr/realisations/2018-deux-escargots-sen-vont/"

[[redirects]]
from = "/projets/courts-metrages/index.html"
to = "/fr/realisations/courts-metrages/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/fr/equipe/equipe-editoriale/"

[[redirects]]
from = "/mentions-legales/index.html"
to = "/fr/mentions-legales/"

[[redirects]]
from = "/projets/2018-deux-escargots-sen-vont/index.html"
to = "/fr/realisations/2018-deux-escargots-sen-vont/"

[[redirects]]
from = "/politique-de-confidentialite/index.html"
to = "/fr/politique-de-confidentialite/"

