[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/plan-du-site/"
to = "/fr/plan-du-site/"

[[redirects]]
from = "/fr/projets/courts-metrages/"
to = "/fr/realisations/courts-metrages/"

[[redirects]]
from = "/fr/biographie/"
to = "/fr/a-propos/"

[[redirects]]
from = "/projets/"
to = "/fr/realisations/"

[[redirects]]
from = "/actualites/"
to = "/fr/actualites/"

[[redirects]]
from = "/fr/projets/"
to = "/fr/realisations/"

[[redirects]]
from = "/accessibilite/"
to = "/fr/accessibilite/"

[[redirects]]
from = "/equipe/"
to = "/fr/equipe/"

[[redirects]]
from = "/organisations/"
to = "/fr/organisations/"

[[redirects]]
from = "/fr/projets/2018-deux-escargots-sen-vont/"
to = "/fr/realisations/2018-deux-escargots-sen-vont/"

[[redirects]]
from = "/projets/courts-metrages/"
to = "/fr/realisations/courts-metrages/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/fr/equipe/equipe-editoriale/"

[[redirects]]
from = "/mentions-legales/"
to = "/fr/mentions-legales/"

[[redirects]]
from = "/projets/2018-deux-escargots-sen-vont/"
to = "/fr/realisations/2018-deux-escargots-sen-vont/"

[[redirects]]
from = "/politique-de-confidentialite/"
to = "/fr/politique-de-confidentialite/"

